# infretis config

[dask]
workers = 1
wmdrun = ['1',
	  '1',
	  '1',
	  '1',]

[simulation]
interfaces = [10, 15, 20, 25, 30, 31, 90]

steps = 60
seed = 0
load_dir = 'load'
shooting_moves = ['sh', 'sh', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf', 'wf']

[simulation.tis_set]
maxlength = 2000
allowmaxlength = false
zero_momentum = true # momentum true
n_jumps = 2
interface_cap = 70.0

[engine]
class = 'lammps'
engine = 'lmp'
timestep = 2.0
input_path = 'lammps_input'
lmp = 'lmp_mpi'
subcycles = 3
temperature = 123

[orderparameter]
class = 'puckering'
index = [2,5,11,8,1,0]
periodic = true

[output]
backup = 'backup'
data_dir = "./"
order-file = 1
energy-file = 1
trajectory-file = -1
screen = 1
pattern = 1
